# Generated by Django 4.2.5 on 2023-09-15 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=255)),
                ('function_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('source_code', models.TextField()),
                ('docstring', models.TextField()),
            ],
        ),
    ]
